drop table if exists member,item CASCADE;
create table member
(
    member_id   bigint generated by default as identity,
    name varchar(255),
    age int,
    primary key (id)
);
create table item
(
    item_id  bigint generated by default as identity ,
    name varchar(255),
    price int,
    quantity int,
    primary key (id)
)